### ISSUE TITLE
create-react-native-app myapp

### ISSUE THREAD

**Issue by shwetaahuja123** [expo/create-react-native-app#822]
✖ Something went wrong in downloading and extracting the project files.

I am seeing above error message with create-react-native-app.
Please suggest fix.

**Comment by petrbela** [comment]
I can confirm. This is what I'm getting when running `npx create-react-native-app exponext`

```sh
Creating a new React Native app in /Users/petrbela/code/exponext.

Using package manager as yarnpkg with yarn interface.
Installing packages. This might take a couple minutes.
Installing react-native-scripts...

yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
warning react-native-scripts > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 20 new dependencies.
info Direct dependencies
└─ react-native-scripts@2.0.1
info All dependencies
├─ ansi-styles@3.2.1
├─ babel-runtime@6.26.0
├─ chalk@2.4.2
├─ color-convert@1.9.3
├─ color-name@1.1.3
├─ core-js@2.6.11
├─ cross-spawn@5.1.0
├─ escape-string-regexp@1.0.5
├─ has-flag@3.0.0
├─ isexe@2.0.0
├─ lru-cache@4.1.5
├─ minimist@1.2.5
├─ pseudomap@1.0.2
├─ react-native-scripts@2.0.1
├─ regenerator-runtime@0.11.1
├─ shebang-command@1.2.0
├─ shebang-regex@1.0.0
├─ supports-color@5.5.0
├─ which@1.3.1
└─ yallist@2.1.2
✨  Done in 1.17s.
(node:33096) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/petrbela/code/exponext/node_modules/react-native-scripts/build/scripts/init.js'
Require stack:
- /Users/petrbela/.config/yarn/global/node_modules/create-react-native-app/build/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at _callee2$ (/Users/petrbela/.config/yarn/global/node_modules/create-react-native-app/build/index.js:128:32)
    at tryCatch (/Users/petrbela/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/petrbela/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:355:22)
    at Generator.prototype.<computed> [as next] (/Users/petrbela/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/petrbela/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /Users/petrbela/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
(node:33096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by EvanBacon** [comment]
The first error is just a general issue with no actionable information. The second is due to the legacy version of crna being installed on the machine. npx is using the globally installed version rather than the latest. Please uninstall the global package `npm uninstall -g create-react-native-app` and try again.
