### ISSUE TITLE
Error in creating react native app - react-native-scripts not found

### ISSUE THREAD

**Issue by joneshjain** [expo/create-react-native-app#828]
```
(node:17904) UnhandledPromiseRejectionWarning: Error: Cannot find module 'c:\Use
rs\Manoj\Documents\coursera\ReactNative\restro\node_modules\react-native-scripts
\build\scripts\init.js'
Require stack:
- C:\Users\Manoj\AppData\Local\Yarn\Data\global\node_modules\create-react-native
-app\build\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)

    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at _callee2$ (C:\Users\Manoj\AppData\Local\Yarn\Data\global\node_modules\cre
ate-react-native-app\build\index.js:128:32)
    at tryCatch (C:\Users\Manoj\AppData\Local\Yarn\Data\global\node_modules\rege
nerator-runtime\runtime.js:62:40)
    at Generator.invoke [as _invoke] (C:\Users\Manoj\AppData\Local\Yarn\Data\glo
bal\node_modules\regenerator-runtime\runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (C:\Users\Manoj\AppData\Local\Ya
rn\Data\global\node_modules\regenerator-runtime\runtime.js:114:21)
    at step (C:\Users\Manoj\AppData\Local\Yarn\Data\global\node_modules\babel-ru
ntime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\Manoj\AppData\Local\Yarn\Data\global\node_modules\babel-runtime\
helpers\asyncToGenerator.js:28:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17904) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). To termin
ate the node process on unhandled promise rejection, use the CLI flag `--unhandl
ed-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejecti
ons_mode). (rejection id: 1)
(node:17904) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.

c:\Users\Manoj\Documents\coursera\ReactNative>
```

**Comment by EvanBacon** [comment]
This is due to the legacy version of `create-react-native-app` being installed on your computer. npx is using the globally installed version rather than the latest. Please uninstall the global package `npm uninstall -g create-react-native-app` and try again.
