### ISSUE TITLE
npx create-react-native-app fails on fresh install

### ISSUE THREAD

**Issue by robbie-c** [expo/create-react-native-app#845]
**Describe the bug**
This error message pretty much sums it up:
`error Couldn't find package "@expo/vector-icons@^10.0.2" required by "expo@~38.0.9" on the "npm" registry.`

**To Reproduce**
npx create-react-native-app testrn

**Expected behavior**
Creates fresh expo app

**Screenshots**
Not a screenshot, but here is my console output:

```
➜  Projects npx create-react-native-app testrn
npx: installed 1 in 1.126s
✔ How would you like to start › Default new app
✔ Downloaded and extracted project files.

🧶 Using Yarn to install packages. You can pass --use-npm to use npm instead.

✖ Something when wrong installing JavaScript dependencies. Check your yarn logs. Continuing to initialize the app.
⚠️  Something when wrong running `pod install` in the `ios` directory. Continuing with initializing the project, you can debug this afterwards.

✅ Your project is ready!

To run your project, navigate to the directory and run one of the following yarn commands.

- cd testrn
- yarn android
- yarn ios
- yarn web

⚠️  Before running your app on iOS, make sure you have CocoaPods installed and initialize the project:

  cd testrn/ios
  npx pod-install

➜  Projects cd testrn/ios
➜  ios git:(master)   npx pod-install
npx: installed 1 in 0.786s
Scanning for pods...
1.9.3
> pod install

[!] Invalid `Podfile` file: cannot load such file -- /Users/robbie/Projects/testrn/node_modules/react-native-unimodules/cocoapods.rb.

 #  from /Users/robbie/Projects/testrn/ios/Podfile:2
 #  -------------------------------------------
 #  platform :ios, '10.0'
 >  require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
 #  require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
 #  -------------------------------------------

Aborting run
An unexpected error was encountered. Please report it as a bug:
Error
    at CocoaPodsPackageManager._installAsync (/Users/robbie/.npm/_npx/6021/lib/node_modules/pod-install/build/index.js:2:76001)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

➜  ios git:(master) ls
Podfile          testrn           testrn.xcodeproj
➜  ios git:(master) yarn
yarn install v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find package "@expo/vector-icons@^10.0.2" required by "expo@~38.0.9" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
warning expo > expo-error-recovery > fbjs > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning expo > fbemitter > fbjs > core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
Error: Couldn't find package "@unimodules/react-native-adapter@~5.4.0" required by "expo@~38.0.9" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@unimodules/core@~5.3.0" required by "expo@~38.0.9" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@expo/websql@^1.0.1" required by "expo-sqlite@~8.2.1" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Couldn't find package "@expo/configure-splash-screen@0.1.13" required by "expo-splash-screen@^0.5.0" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:750:123)
    at PackageRequest.<anonymous> (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:36539:17)
    at Generator.throw (<anonymous>)
    at step (/Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:310:30)
    at /Users/robbie/.nvm/versions/node/v12.16.1/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Desktop (please complete the following information):**
OSX 10.15.5
Yarn 1.22.4
Node v12.16.1
Npx version 6.13.4

**Smartphone (please complete the following information):**
n/a

**Additional context**
ohmyzsh shell formatting, so lines with my commands start with `➜` when you see `➜  ios git:(master) ls` that means I typed `ls` in the `ios`folder

**Comment by robbie-c** [comment]
Closing because this is clearly something weird going on with my machine, as https://www.npmjs.com/package/@expo/vector-icons/v/10.0.2 clearly does exist
