### ISSUE TITLE
Help !!!  Unable to solve it tried whatever is available in google "The development server returned response error code 500

### ISSUE THREAD

**Issue by Sana720** [expo/create-react-native-app#931]
![Screenshot (73)](https://github.com/expo/create-react-native-app/assets/58582391/22d3df4f-d5a6-4e71-9402-9d8c22ba3146)
**Describe the bug**
error: TypeError: dependencies is not iterable
    at Graph._resolveDependencies (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:452:23)
    at Graph._processModule (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:267:38)
    at async Graph._addDependency (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:378:20)
    at async Promise.all (index 33)
    at async Graph._processModule (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:328:5)
    at async Graph._addDependency (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:378:20)
    at async Promise.all (index 3)
    at async Graph._processModule (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:328:5)
    at async Graph._traverseDependenciesForSingleFile (C:\Users\saahm\OneDrive\Desktop\varcast-app-master\node_modules\@react-native-community\cli-plugin-metro\node_modules\metro\src\DeltaBundler\Graph.js:255:5)
    at async Promise.all (index 0)

**Comment by natejhowe** [comment]
Did you ever figure this out? I've been banging my head against the wall attempting to debug this error.

**Comment by natejhowe** [comment]
@Sana720 Delete your Temp folder located here C:\Users\{user}\AppData\Local\Temp. Then try again. Fixed it for me.

**Comment by ivstiv** [comment]
Had the same issue today, my Windows bluescreened so that must have corrupted some of my cache. After wiping the Temp folder that @natejhowe mentioned the problem went away!

**Comment by Manlikevee** [comment]
npx expo install --fix  fixed it for me

**Comment by kerimovok** [comment]
> @Sana720 Delete your Temp folder located here C:\Users{user}\AppData\Local\Temp. Then try again. Fixed it for me.

It helped me too, thx!

**Comment by Aaqibraza098** [comment]
> @Sana720 Delete your Temp folder located here C:\Users{user}\AppData\Local\Temp. Then try again. Fixed it for me.

This one helped . Thanks

**Comment by mugabe00** [comment]
> npx expo install --fix

this one helped me . thanks

**Comment by shaheer741** [comment]
> @Sana720 Delete your Temp folder located here C:\Users{user}\AppData\Local\Temp. Then try again. Fixed it for me.

solved for me

**Comment by mikeisadev** [comment]
I had the same problem and I fixed it right now. 

Instead of going into the "Temp" folder inside AppData/Local deleting the interested temp and cache files, you can do the following steps:

- delete ".expo" folder inside your react native project
- run this command `npm cache clean --force` to clear the global npm cache
- then run this command `npx expo start --clear` to restart the development server and to clear the transformation javascript/typescript/jsx/tsx files starting fresh

These commands helped me to solve the problem. Yes, you can go and clear cache files and temp files inside your PC folders inside "AppData/Local/Temp", but this approach will save you time with a direct CLI command.

I want to add more:
If you need to establish a tunnel connection to see your react native app through expo go on your smartphone do this:
- `npm cache clean --force`
- `npx expo start --clear`
- then "ctrl+c" to stop everything
- `npx expo start --tunnel` to restart the server in a tunnel

Or you can combine the two last commands `npx expo start --clear` and `npx expo start --tunnel` into `npx expo start --clear --tunnel` after doing `npm cache clean --force`. But `npx expo start --clear --tunnel` gave me errors, so do the step by step procedure dividing the two commands.

Hope it helps.

**Comment by Vinaykpro** [comment]
Cool so deleting the temp folder is the only working way for me these cache clean commands didn't fix my problem...

**Comment by AslamNS** [comment]
> [@Sana720](https://github.com/Sana720) Delete your Temp folder located here C:\Users{user}\AppData\Local\Temp. Then try again. Fixed it for me.

this worked for me

**Comment by Shahtaymur** [comment]
> [@Sana720](https://github.com/Sana720) Delete your Temp folder located here C:\Users{user}\AppData\Local\Temp. Then try again. Fixed it for me.

It helped me too, thx!

**Comment by leostark221** [comment]
> npx expo install --fix fixed it for me

Worked for me as well. Thanks it was a different issue but somewhat similar
